# Generated by Django 2.2 on 2020-02-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191115_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_halls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.CharField(max_length=5)),
            ],
        ),
    ]
