# Generated by Django 2.2 on 2020-03-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_exam_halls'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_halls',
            name='columns',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exam_halls',
            name='rows',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
